title: The Microbial Biosignatures Project
description: A research collaboration exploring microbialite biosignatures
baseurl: "/microbialbiosignatures.github.io"
url: "https://tahickson.github.io"

# Build settings
permalink: pretty
markdown: kramdown
kramdown:
  parse_block_html: true
  input: GFM

# Exclude these files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - OLD_HTML/
